---
apiVersion: v1
kind: Namespace
metadata:
  name: minishop

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minishop-config
  namespace: minishop
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "shop"
  POSTGRES_USER: "shop"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  ERP_BASE_URL: "http://erp.minishop.internal:8080" # пример внешней зависимости (вне k8s)

---
apiVersion: v1
kind: Secret
metadata:
  name: minishop-secret
  namespace: minishop
type: Opaque
stringData:
  POSTGRES_PASSWORD: "shop-pass"
  RABBITMQ_DEFAULT_USER: "shop"
  RABBITMQ_DEFAULT_PASS: "rabbit-pass"

# -------------------------
# Postgres (DB)
# -------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: minishop
spec:
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: minishop
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minishop-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

# -------------------------
# RabbitMQ (queue)
# -------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: minishop
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: minishop
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mgmt
      port: 15672
      targetPort: 15672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: minishop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: minishop-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: minishop-secret
                  key: RABBITMQ_DEFAULT_PASS
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data

# -------------------------
# App services (>=3)
# -------------------------

# catalog-service (mock)
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: minishop
spec:
  selector:
    app: catalog
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: minishop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: hashicorp/http-echo:1.0
          args: ["-listen=:8080", "-text=catalog ok"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

# order-service (mock)
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: minishop
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: minishop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: hashicorp/http-echo:1.0
          args: ["-listen=:8080", "-text=orders ok"]
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minishop-secret
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: RABBITMQ_PORT
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

# web-frontend (nginx reverse-proxy)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx-conf
  namespace: minishop
data:
  default.conf: |
    server {
      listen 80;

      location = /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
      }

      location / {
        return 200 "minishop ui ok\ntry: /catalog and /orders\n";
        add_header Content-Type text/plain;
      }

      location /catalog {
        proxy_pass http://catalog:8080/;
      }

      location /orders {
        proxy_pass http://orders:8080/;
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: minishop
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: minishop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: web-nginx-conf

# -------------------------
# Ingress
# -------------------------
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minishop-ingress
  namespace: minishop
spec:
  ingressClassName: nginx
  rules:
    - host: minishop.local
      http:
        paths:
          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 8080
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80

# -------------------------
# Job: init DB (example)
# -------------------------
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: minishop
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: postgres:16-alpine
          env:
            - name: PGHOST
              value: "postgres"
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_PORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_DB
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: minishop-secret
                  key: POSTGRES_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "waiting for postgres..."
              until pg_isready; do sleep 2; done
              echo "init schema..."
              psql <<'SQL'
              create table if not exists orders(
                id bigserial primary key,
                created_at timestamptz not null default now(),
                payload jsonb not null
              );
              insert into orders(payload) values ('{"seed":"ok"}')
              on conflict do nothing;
              SQL
              echo "done."
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

# -------------------------
# CronJob: publish heartbeat to RabbitMQ (через management API)
# -------------------------
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rabbit-heartbeat
  namespace: minishop
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hb
              image: curlimages/curl:8.5.0
              env:
                - name: RABBITMQ_DEFAULT_USER
                  valueFrom:
                    secretKeyRef:
                      name: minishop-secret
                      key: RABBITMQ_DEFAULT_USER
                - name: RABBITMQ_DEFAULT_PASS
                  valueFrom:
                    secretKeyRef:
                      name: minishop-secret
                      key: RABBITMQ_DEFAULT_PASS
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  curl -sS -u "${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}" \
                    -H "content-type: application/json" \
                    -X POST "http://rabbitmq:15672/api/exchanges/%2F/amq.default/publish" \
                    -d '{"properties":{},"routing_key":"heartbeat","payload":"heartbeat","payload_encoding":"string"}' \
                    | cat
              resources:
                requests:
                  cpu: "25m"
                  memory: "32Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"